apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsehub
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: pulsehub=fullstackjam/pulsehub
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/fullstackjam/pulsehub
    targetRevision: master
    path: helm/pulsehub
  destination:
    name: in-cluster
    namespace: pulsehub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
