apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pulsehub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pulsehub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pulsehub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pulsehub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: pulsehub
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 64Mi
