{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pulsehub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pulsehub.labels" . | nindent 4 }}
  annotations:
    # External DNS annotations for Cloudflare Tunnel
    external-dns.alpha.kubernetes.io/target: "homelab-tunnel.fullstackjam.com"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    
    # ArgoCD sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "pulsehub.fullname" . }}
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ include "pulsehub.fullname" . }}-tls
{{- end }}
