apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pulsehub-ingress
spec:
  rules:
  - host: pulsehub.fullstackjam.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pulsehub-service
            port:
              number: 3001