apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulsehub.fullname" . }}
  labels:
    {{- include "pulsehub.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pulsehub.selectorLabels" . | nindent 4 }}
